{% set name = "localstack" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 81e39304e83e4b888f38361045d5df0f4d42947cd1d68327ca46ce103aea6be0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python

  run:
    - boto3
    - docopt
    - localstack-client
    - localstack-ext
    - python
    - six
    - subprocess32        # [py2k]

test:
  imports:
    - localstack
    - localstack.dashboard
    - localstack.services
    - localstack.services.apigateway
    - localstack.services.awslambda
    - localstack.services.cloudformation
    - localstack.services.dynamodb
    - localstack.services.dynamodbstreams
    - localstack.services.es
    - localstack.services.firehose
    - localstack.services.iam
    - localstack.services.kinesis
    - localstack.services.s3
    - localstack.services.sns
    - localstack.services.sqs
    - localstack.services.stepfunctions
    - localstack.stepfunctions
    - localstack.utils
    - localstack.utils.analytics
    - localstack.utils.aws
    - localstack.utils.cloudformation
    - localstack.utils.cloudwatch
    - localstack.utils.kinesis
    - localstack.utils.server

about:
  home: https://github.com/localstack/localstack
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: An easy-to-use test/mocking framework for developing Cloud applications
  doc_url: https://pypi.org/project/localstack/
  dev_url: https://github.com/localstack/localstack

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - rluria14
