travis:
  secure:
    BINSTAR_TOKEN: WUJZBQdA+ia5GU6KWWYpX3NLqCsHPS8RmQMtbQLeX9M4mygoqvqFe4JZm4BdCNqY5jttYzc2HGXKG4qvHbiBWaG9PoweC3AsxHD2JdgWWSEgHqfIIpmsvkMrnaVvcvP2BvcBYQUPZEv98atHBOZU1gTR7GL/T0ygRg3ReRpIYZg4bOT5bfHr4wtDXgoY3SCexBGzSKDbVMVbV09GgdHGtQNXvbZ5Q9yXhJlxQJoGUCOtMD/AwBNlHKJbyWuwJ6XNrKpsvmTvNfXvXU2vs14Fxd9QR6I0WEVh8sf7pN1i0m1m9G8B8tEFJFEzzQJd/eUY8T3d15s2xY6TnVQn5iwMr+mPCt1283LO7YSRyjVbjKEsTs9AMg1k06vJDgv9gFty5dAamxIZuCxUZpoyfJtRfECs09SokFa6716eafuZZY6jEmgzeAigZ9tjBi++QCmdCnwM3btLhpYhiYCHhXwvq1Dk8+NdGVa2JKEMqr6PtTkDNopvv7f/vi4uX55ImQmkpoAsJSqBshawPVMO1DDE960LX3o1I46grKD4DrYuZ0VUmI/PshteCedyWPYkBc2VGYj0Yq9X8CKVBVAuzidcSh0VaihjcutUO5s2VbPy42wgSYYdfIiQ0yzFN/RdsiA/ZKIpYL9eZB1Hk3rI/+g63PDWZVuv2BeIc1UOJ72PdTw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
